apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: QXdzMTIzNCo=        
  mysql-user: dXN1YXJpbw==                
  mysql-password: bW9uZGE=                 
