apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: QXdzMTIzNCo=        # Base64 encoded 'Aws1234*'
  mysql-user: dXN1YXJpbw==                 # Base64 encoded 'usuario'
  mysql-password: bW9uZGE=                 # Base64 encoded 'monda'
